
CREATE SEQUENCE profile_social_profiles_id_seq
	START WITH 1
	INCREMENT BY 1
	NO MAXVALUE
	NO MINVALUE
	CACHE 1;

CREATE SEQUENCE profiles_id_seq
	START WITH 1
	INCREMENT BY 1
	NO MAXVALUE
	NO MINVALUE
	CACHE 1;

CREATE TABLE admin_selection_locks (
	event_id integer NOT NULL,
	locked_by_profile_id integer NOT NULL,
	lock_started_at timestamp with time zone DEFAULT "now"() NOT NULL,
	lock_expires_at timestamp with time zone NOT NULL
);


CREATE TABLE app_settings (
	"key" "text" NOT NULL,
	value_json "jsonb" NOT NULL,
	updated_at timestamp with time zone DEFAULT "now"() NOT NULL
);


CREATE TABLE event_performer_selections (
	id bigint NOT NULL,
	event_id integer NOT NULL,
	profile_id integer NOT NULL,
	requested_date_id bigint,
	slot_number integer,
	status "text" DEFAULT 'selected'::"text" NOT NULL,
	selected_at timestamp with time zone DEFAULT "now"() NOT NULL,
	selected_by_profile_id integer,
	notes "text"
);


CREATE TABLE moderation_actions (
	id bigint NOT NULL,
	draft_id bigint NOT NULL,
	moderator_profile_id integer NOT NULL,
	"action" "text" NOT NULL,
	reason "text",
	acted_at timestamp with time zone DEFAULT "now"() NOT NULL
);


CREATE TABLE profile_submission_drafts (
	id bigint NOT NULL,
	profile_id integer,
	email "text" NOT NULL,
	profile_type "text" NOT NULL,
	display_name "text" NOT NULL,
	first_name "text",
	last_name "text",
	contact_phone "text",
	is_email_public boolean DEFAULT false NOT NULL,
	is_name_public boolean DEFAULT false NOT NULL,
	artist_bio "text",
	is_artist_bio_public boolean DEFAULT false NOT NULL,
	status "text" DEFAULT 'pending'::"text" NOT NULL,
	submitted_at timestamp with time zone DEFAULT "now"() NOT NULL,
	submitted_by_email "text" NOT NULL,
	reviewed_at timestamp with time zone,
	reviewed_by_profile_id integer,
	denial_reason "text",
	additional_info "text"
);


CREATE TABLE profile_submission_social_profiles (
	id bigint NOT NULL,
	draft_id bigint NOT NULL,
	social_platform_id integer NOT NULL,
	profile_name "text" NOT NULL,
	sort_order integer DEFAULT 0 NOT NULL
);


CREATE TABLE requested_dates (
	id bigint NOT NULL,
	draft_id bigint NOT NULL,
	event_id integer NOT NULL,
	status "text" DEFAULT 'requested'::"text" NOT NULL,
	requested_at timestamp with time zone DEFAULT "now"() NOT NULL,
	availability_responded_at timestamp with time zone,
	selected_at timestamp with time zone,
	selected_by_profile_id integer,
	availability_email_sent_at timestamp with time zone,
	moderator_reminder_sent_at timestamp with time zone
);

DO $$
BEGIN
  IF EXISTS (
    SELECT 1
    FROM information_schema.columns
    WHERE table_schema = 'public'
      AND table_name = 'profile_submission_drafts'
      AND column_name = 'id'
      AND is_identity = 'NO'
  ) THEN
    EXECUTE 'ALTER TABLE public.profile_submission_drafts ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY';
  END IF;
END;
$$;

DO $$
BEGIN
  IF EXISTS (
    SELECT 1
    FROM information_schema.columns
    WHERE table_schema = 'public'
      AND table_name = 'profile_submission_social_profiles'
      AND column_name = 'id'
      AND is_identity = 'NO'
  ) THEN
    EXECUTE 'ALTER TABLE public.profile_submission_social_profiles ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY';
  END IF;
END;
$$;

DO $$
BEGIN
  IF EXISTS (
    SELECT 1
    FROM information_schema.columns
    WHERE table_schema = 'public'
      AND table_name = 'requested_dates'
      AND column_name = 'id'
      AND is_identity = 'NO'
  ) THEN
    EXECUTE 'ALTER TABLE public.requested_dates ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY';
  END IF;
END;
$$;

DO $$
BEGIN
  IF EXISTS (
    SELECT 1
    FROM information_schema.columns
    WHERE table_schema = 'public'
      AND table_name = 'moderation_actions'
      AND column_name = 'id'
      AND is_identity = 'NO'
  ) THEN
    EXECUTE 'ALTER TABLE public.moderation_actions ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY';
  END IF;
END;
$$;

DO $$
BEGIN
  IF EXISTS (
    SELECT 1
    FROM information_schema.columns
    WHERE table_schema = 'public'
      AND table_name = 'event_performer_selections'
      AND column_name = 'id'
      AND is_identity = 'NO'
  ) THEN
    EXECUTE 'ALTER TABLE public.event_performer_selections ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY';
  END IF;
END;
$$;

DO $$
BEGIN
  IF EXISTS (
    SELECT 1
    FROM information_schema.columns
    WHERE table_schema = 'public'
      AND table_name = 'action_tokens'
      AND column_name = 'id'
      AND is_identity = 'NO'
  ) THEN
    EXECUTE 'ALTER TABLE public.action_tokens ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY';
  END IF;
END;
$$;

SELECT setval(
  pg_get_serial_sequence('public.profile_submission_drafts', 'id'),
  COALESCE((SELECT MAX(id) FROM public.profile_submission_drafts), 0) + 1,
  false
);

SELECT setval(
  pg_get_serial_sequence('public.profile_submission_social_profiles', 'id'),
  COALESCE((SELECT MAX(id) FROM public.profile_submission_social_profiles), 0) + 1,
  false
);

SELECT setval(
  pg_get_serial_sequence('public.requested_dates', 'id'),
  COALESCE((SELECT MAX(id) FROM public.requested_dates), 0) + 1,
  false
);

SELECT setval(
  pg_get_serial_sequence('public.moderation_actions', 'id'),
  COALESCE((SELECT MAX(id) FROM public.moderation_actions), 0) + 1,
  false
);

SELECT setval(
  pg_get_serial_sequence('public.event_performer_selections', 'id'),
  COALESCE((SELECT MAX(id) FROM public.event_performer_selections), 0) + 1,
  false
);

SELECT setval(
  pg_get_serial_sequence('public.action_tokens', 'id'),
  COALESCE((SELECT MAX(id) FROM public.action_tokens), 0) + 1,
  false
);

SELECT setval(
  pg_get_serial_sequence('public.profiles', 'id'),
  COALESCE((SELECT MAX(id) FROM public.profiles), 0) + 1,
  false
);

SELECT setval(
  pg_get_serial_sequence('public.profile_social_profiles', 'id'),
  COALESCE((SELECT MAX(id) FROM public.profile_social_profiles), 0) + 1,
  false
);


ALTER TABLE events
	ADD COLUMN admin_selection_email_sent_at timestamp with time zone;

ALTER TABLE profile_social_profiles
	ALTER COLUMN id SET DEFAULT "nextval"('"public"."profile_social_profiles_id_seq"'::"regclass");

ALTER TABLE profiles
	ADD COLUMN contact_phone "text",
	ADD COLUMN is_profile_approved boolean DEFAULT false NOT NULL,
	ADD COLUMN is_moderator boolean DEFAULT false NOT NULL,
	ADD COLUMN is_admin boolean DEFAULT false NOT NULL,
	ADD COLUMN profile_visible_from "date",
	ADD COLUMN profile_expires_on "date" DEFAULT (CURRENT_DATE + '100 years'::interval) NOT NULL,
	ADD COLUMN approved_at timestamp with time zone,
	ADD COLUMN approved_by_profile_id integer,
	ALTER COLUMN id SET DEFAULT "nextval"('"public"."profiles_id_seq"'::"regclass");

ALTER TABLE social_platforms
	ADD COLUMN input_label "text",
	ADD COLUMN input_placeholder "text",
	ADD COLUMN input_help "text";

ALTER SEQUENCE profile_social_profiles_id_seq
	OWNED BY "public"."profile_social_profiles"."id";

ALTER SEQUENCE profiles_id_seq
	OWNED BY "public"."profiles"."id";

CREATE OR REPLACE FUNCTION ensure_staff_profile_is_valid(target_profile_id integer) RETURNS "void"
    LANGUAGE "plpgsql"
    AS $$
DECLARE
  profile_row profiles%ROWTYPE;
BEGIN
  IF target_profile_id IS NULL THEN
    RETURN;
  END IF;

  SELECT *
  INTO profile_row
  FROM profiles
  WHERE id = target_profile_id;

  IF NOT FOUND THEN
    RETURN;
  END IF;

  IF NOT (profile_row.is_moderator OR profile_row.is_admin) THEN
    RETURN;
  END IF;

  IF profile_row.profile_type <> 'person' THEN
    RAISE EXCEPTION 'Only person profiles can be moderators or admins.';
  END IF;

  IF NOT EXISTS (
    SELECT 1
    FROM profile_roles pr
    WHERE pr.profile_id = target_profile_id
      AND pr.role = 'volunteer'
  ) THEN
    RAISE EXCEPTION 'Moderator/admin profiles must also have the volunteer role.';
  END IF;
END;
$$;

CREATE OR REPLACE FUNCTION trigger_validate_staff_profile_from_profiles() RETURNS "trigger"
    LANGUAGE "plpgsql"
    AS $$
BEGIN
  PERFORM ensure_staff_profile_is_valid(NEW.id);
  RETURN NEW;
END;
$$;

CREATE OR REPLACE FUNCTION trigger_validate_staff_profile_from_roles() RETURNS "trigger"
    LANGUAGE "plpgsql"
    AS $$
BEGIN
  IF TG_OP = 'DELETE' THEN
    PERFORM ensure_staff_profile_is_valid(OLD.profile_id);
    RETURN OLD;
  END IF;

  PERFORM ensure_staff_profile_is_valid(NEW.profile_id);
  RETURN NEW;
END;
$$;

ALTER TABLE admin_selection_locks
	ADD CONSTRAINT admin_selection_locks_pkey PRIMARY KEY ("event_id");

ALTER TABLE app_settings
	ADD CONSTRAINT app_settings_pkey PRIMARY KEY ("key");

ALTER TABLE event_performer_selections
	ADD CONSTRAINT event_performer_selections_pkey PRIMARY KEY ("id");

ALTER TABLE moderation_actions
	ADD CONSTRAINT moderation_actions_pkey PRIMARY KEY ("id");

ALTER TABLE profile_submission_drafts
	ADD CONSTRAINT profile_submission_drafts_pkey PRIMARY KEY ("id");

ALTER TABLE profile_submission_social_profiles
	ADD CONSTRAINT profile_submission_social_profiles_pkey PRIMARY KEY ("id");

ALTER TABLE requested_dates
	ADD CONSTRAINT requested_dates_pkey PRIMARY KEY ("id");

ALTER TABLE action_tokens
	ADD CONSTRAINT action_tokens_draft_id_fkey FOREIGN KEY ("draft_id") REFERENCES "public"."profile_submission_drafts"("id") ON DELETE CASCADE;

ALTER TABLE action_tokens
	ADD CONSTRAINT action_tokens_requested_date_id_fkey FOREIGN KEY ("requested_date_id") REFERENCES "public"."requested_dates"("id") ON DELETE CASCADE;

ALTER TABLE admin_selection_locks
	ADD CONSTRAINT admin_selection_locks_event_id_fkey FOREIGN KEY ("event_id") REFERENCES "public"."events"("id") ON DELETE CASCADE;

ALTER TABLE admin_selection_locks
	ADD CONSTRAINT admin_selection_locks_locked_by_profile_id_fkey FOREIGN KEY ("locked_by_profile_id") REFERENCES "public"."profiles"("id") ON DELETE CASCADE;

ALTER TABLE event_performer_selections
	ADD CONSTRAINT event_performer_selections_status_check CHECK (("status" = ANY (ARRAY['selected'::"text", 'declined'::"text", 'cancelled'::"text", 'standby'::"text", 'reserve'::"text"])));

ALTER TABLE event_performer_selections
	ADD CONSTRAINT event_performer_selections_event_id_profile_id_key UNIQUE ("event_id", "profile_id");

ALTER TABLE event_performer_selections
	ADD CONSTRAINT event_performer_selections_event_id_fkey FOREIGN KEY ("event_id") REFERENCES "public"."events"("id") ON DELETE CASCADE;

ALTER TABLE event_performer_selections
	ADD CONSTRAINT event_performer_selections_profile_id_fkey FOREIGN KEY ("profile_id") REFERENCES "public"."profiles"("id") ON DELETE CASCADE;

ALTER TABLE event_performer_selections
	ADD CONSTRAINT event_performer_selections_requested_date_id_fkey FOREIGN KEY ("requested_date_id") REFERENCES "public"."requested_dates"("id") ON DELETE SET NULL;

ALTER TABLE event_performer_selections
	ADD CONSTRAINT event_performer_selections_selected_by_profile_id_fkey FOREIGN KEY ("selected_by_profile_id") REFERENCES "public"."profiles"("id");

ALTER TABLE moderation_actions
	ADD CONSTRAINT moderation_actions_action_check CHECK (("action" = ANY (ARRAY['approved'::"text", 'denied'::"text"])));

ALTER TABLE moderation_actions
	ADD CONSTRAINT moderation_actions_draft_id_fkey FOREIGN KEY ("draft_id") REFERENCES "public"."profile_submission_drafts"("id") ON DELETE CASCADE;

ALTER TABLE moderation_actions
	ADD CONSTRAINT moderation_actions_moderator_profile_id_fkey FOREIGN KEY ("moderator_profile_id") REFERENCES "public"."profiles"("id");

ALTER TABLE profile_submission_drafts
	ADD CONSTRAINT profile_submission_drafts_profile_type_check CHECK (("profile_type" = ANY (ARRAY['person'::"text", 'group'::"text"])));

ALTER TABLE profile_submission_drafts
	ADD CONSTRAINT profile_submission_drafts_status_check CHECK (("status" = ANY (ARRAY['pending'::"text", 'approved'::"text", 'denied'::"text", 'superseded'::"text"])));

ALTER TABLE profile_submission_drafts
	ADD CONSTRAINT profile_submission_drafts_profile_id_fkey FOREIGN KEY ("profile_id") REFERENCES "public"."profiles"("id") ON DELETE CASCADE;

ALTER TABLE profile_submission_drafts
	ADD CONSTRAINT profile_submission_drafts_reviewed_by_profile_id_fkey FOREIGN KEY ("reviewed_by_profile_id") REFERENCES "public"."profiles"("id");

ALTER TABLE profile_submission_social_profiles
	ADD CONSTRAINT profile_submission_social_pro_draft_id_social_platform_id_p_key UNIQUE ("draft_id", "social_platform_id", "profile_name");

ALTER TABLE profile_submission_social_profiles
	ADD CONSTRAINT profile_submission_social_profiles_draft_id_fkey FOREIGN KEY ("draft_id") REFERENCES "public"."profile_submission_drafts"("id") ON DELETE CASCADE;

ALTER TABLE profile_submission_social_profiles
	ADD CONSTRAINT profile_submission_social_profiles_social_platform_id_fkey FOREIGN KEY ("social_platform_id") REFERENCES "public"."social_platforms"("id");

ALTER TABLE profiles
	ADD CONSTRAINT profiles_admin_person_check CHECK (((NOT "is_admin") OR ("profile_type" = 'person'::"text")));

ALTER TABLE profiles
	ADD CONSTRAINT profiles_moderator_person_check CHECK (((NOT "is_moderator") OR ("profile_type" = 'person'::"text")));

ALTER TABLE profiles
	ADD CONSTRAINT profiles_approved_by_profile_id_fkey FOREIGN KEY ("approved_by_profile_id") REFERENCES "public"."profiles"("id");

ALTER TABLE requested_dates
	ADD CONSTRAINT requested_dates_status_check CHECK (("status" = ANY (ARRAY['requested'::"text", 'availability_confirmed'::"text", 'availability_cancelled'::"text", 'selected'::"text", 'not_selected'::"text", 'withdrawn'::"text"])));

ALTER TABLE requested_dates
	ADD CONSTRAINT requested_dates_draft_id_event_id_key UNIQUE ("draft_id", "event_id");

ALTER TABLE requested_dates
	ADD CONSTRAINT requested_dates_draft_id_fkey FOREIGN KEY ("draft_id") REFERENCES "public"."profile_submission_drafts"("id") ON DELETE CASCADE;

ALTER TABLE requested_dates
	ADD CONSTRAINT requested_dates_event_id_fkey FOREIGN KEY ("event_id") REFERENCES "public"."events"("id") ON DELETE CASCADE;

ALTER TABLE requested_dates
	ADD CONSTRAINT requested_dates_selected_by_profile_id_fkey FOREIGN KEY ("selected_by_profile_id") REFERENCES "public"."profiles"("id");

CREATE INDEX idx_admin_selection_locks_expires_at ON admin_selection_locks USING "btree" ("lock_expires_at");

CREATE INDEX idx_event_performer_selections_event_status ON event_performer_selections USING "btree" ("event_id", "status");

CREATE INDEX idx_moderation_actions_draft_id ON moderation_actions USING "btree" ("draft_id");

CREATE INDEX idx_profile_submission_drafts_email_status ON profile_submission_drafts USING "btree" ("email", "status");

CREATE INDEX idx_profile_submission_drafts_profile_status ON profile_submission_drafts USING "btree" ("profile_id", "status");

CREATE INDEX idx_profile_submission_social_profiles_draft_id ON profile_submission_social_profiles USING "btree" ("draft_id");

CREATE INDEX idx_profiles_email ON profiles USING "btree" ("email");

CREATE INDEX idx_profiles_is_profile_approved ON profiles USING "btree" ("is_profile_approved");

CREATE INDEX idx_profiles_visible_window ON profiles USING "btree" ("profile_visible_from", "profile_expires_on");

CREATE INDEX idx_requested_dates_draft_id ON requested_dates USING "btree" ("draft_id");

CREATE INDEX idx_requested_dates_event_status ON requested_dates USING "btree" ("event_id", "status");

CREATE TRIGGER trg_profile_roles_ensure_staff_roles
	AFTER INSERT OR UPDATE OF "role" OR DELETE ON profile_roles
	FOR EACH ROW
	EXECUTE PROCEDURE "public"."trigger_validate_staff_profile_from_roles"();

CREATE TRIGGER trg_profiles_ensure_staff_roles
	AFTER INSERT OR UPDATE OF "profile_type", "is_moderator", "is_admin" ON profiles
	FOR EACH ROW
	EXECUTE PROCEDURE "public"."trigger_validate_staff_profile_from_profiles"();
