BEGIN;

CREATE TABLE IF NOT EXISTS locations (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name text NOT NULL,
  address text,
  latitude numeric(9, 6),
  longitude numeric(9, 6),
  UNIQUE (name, address)
);

ALTER TABLE events
  ADD COLUMN IF NOT EXISTS starts_at timestamptz,
  ADD COLUMN IF NOT EXISTS ends_at timestamptz,
  ADD COLUMN IF NOT EXISTS timezone text NOT NULL DEFAULT 'Australia/Sydney',
  ADD COLUMN IF NOT EXISTS location_id integer REFERENCES locations(id) ON DELETE SET NULL;

ALTER TABLE events
  DROP CONSTRAINT IF EXISTS events_ends_at_after_starts_at;

ALTER TABLE events
  ADD CONSTRAINT events_ends_at_after_starts_at
  CHECK (ends_at IS NULL OR starts_at IS NULL OR ends_at > starts_at);

CREATE INDEX IF NOT EXISTS idx_events_starts_at ON events(starts_at);
CREATE INDEX IF NOT EXISTS idx_events_location_id ON events(location_id);

DO $$
BEGIN
  IF EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'emom_forms_writer') THEN
    GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE locations TO emom_forms_writer;
    GRANT USAGE, SELECT, UPDATE ON SEQUENCE locations_id_seq TO emom_forms_writer;
  END IF;
  IF EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'emom_test_forms_writer') THEN
    GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE locations TO emom_test_forms_writer;
    GRANT USAGE, SELECT, UPDATE ON SEQUENCE locations_id_seq TO emom_test_forms_writer;
  END IF;
  IF EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'emom_site_reader') THEN
    GRANT SELECT ON TABLE locations TO emom_site_reader;
  END IF;
END;
$$;

COMMIT;
