BEGIN;

-- Add identity generation to legacy integer PK tables that still rely on
-- manual id assignment. Keep BY DEFAULT to preserve compatibility with any
-- explicit id inserts used by seeds/imports.
DO $$
DECLARE
  item record;
BEGIN
  FOR item IN
    SELECT *
    FROM (
      VALUES
        ('public', 'event_types'),
        ('public', 'social_platforms'),
        ('public', 'events'),
        ('public', 'performances'),
        ('public', 'profile_images')
    ) AS tables_to_update(schema_name, table_name)
  LOOP
    IF NOT EXISTS (
      SELECT 1
      FROM pg_attribute
      WHERE attrelid = format('%I.%I', item.schema_name, item.table_name)::regclass
        AND attname = 'id'
        AND attidentity IN ('a', 'd')
    ) THEN
      EXECUTE format(
        'ALTER TABLE %I.%I ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY',
        item.schema_name,
        item.table_name
      );
    END IF;
  END LOOP;
END;
$$;

-- Ensure the associated sequences are ahead of current maximum ids.
DO $$
DECLARE
  item record;
  sequence_name text;
  max_id bigint;
BEGIN
  FOR item IN
    SELECT *
    FROM (
      VALUES
        ('public', 'event_types', 'id'),
        ('public', 'social_platforms', 'id'),
        ('public', 'events', 'id'),
        ('public', 'performances', 'id'),
        ('public', 'profile_images', 'id')
    ) AS identity_columns(schema_name, table_name, column_name)
  LOOP
    sequence_name := pg_get_serial_sequence(
      format('%I.%I', item.schema_name, item.table_name),
      item.column_name
    );

    IF sequence_name IS NULL THEN
      CONTINUE;
    END IF;

    EXECUTE format(
      'LOCK TABLE %I.%I IN SHARE ROW EXCLUSIVE MODE',
      item.schema_name,
      item.table_name
    );

    EXECUTE format(
      'SELECT COALESCE(MAX(%I), 0) FROM %I.%I',
      item.column_name,
      item.schema_name,
      item.table_name
    )
    INTO max_id;

    EXECUTE format(
      'SELECT setval(%L::regclass, %s, false)',
      sequence_name,
      max_id + 1
    );
  END LOOP;
END;
$$;

COMMIT;
