import s3files from "../_data/s3files.js";
import lightbox from "./lightbox.js";
import { getImageThumbnailResult } from "../_data/imageHelpers.js";
import { loadEmomData } from "../../lib/data/loadEmomData.js";


// WARNING this code was generated by CoPilot, and although it seems to work 
// I'll bet an experienced JS coder could run rings around it. 
// I'm not though - so for now it is what it is. :)

// Image file extensions that should be rendered as lightbox galleries
const IMAGE_EXTENSIONS = new Set(['jpg', 'jpeg', 'png', 'gif']); 

// Build a nested tree node
const makeNode = () => ({ files: [], children: new Map() });

// Helper: sanitize part for URL path (keep letters, numbers, - and _)
const safePart = (s) => String(s).trim().replace(/[^a-zA-Z0-9-_]+/g, '-').replace(/-+/g, '-').replace(/^-|-$/g, '');

function escapeHtml(value) {
  return String(value)
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;")
    .replace(/"/g, "&quot;")
    .replace(/'/g, "&#39;");
}

function extractYouTubeVideoId(value) {
  let input = String(value || "").trim();
  if (!input) return null;

  // Accept pasted iframe embed snippets from YouTube share dialogs.
  if (input.toLowerCase().includes("<iframe")) {
    const srcMatch = input.match(/src=(["'])(.*?)\1/i);
    if (srcMatch && srcMatch[2]) {
      input = srcMatch[2].trim();
    }
  }

  // Allow a raw video ID for manual DB entry.
  if (/^[A-Za-z0-9_-]{11}$/.test(input)) return input;

  try {
    const url = new URL(input);
    const hostname = url.hostname.toLowerCase().replace(/^www\./, "");

    if (hostname === "youtu.be") {
      return (url.pathname.split("/").filter(Boolean)[0] || "").trim() || null;
    }

    if (
      hostname === "youtube.com" ||
      hostname === "m.youtube.com" ||
      hostname === "music.youtube.com" ||
      hostname === "youtube-nocookie.com"
    ) {
      const pathParts = url.pathname.split("/").filter(Boolean);

      if (pathParts[0] === "embed" || pathParts[0] === "shorts" || pathParts[0] === "live") {
        return (pathParts[1] || "").trim() || null;
      }

      const watchId = url.searchParams.get("v");
      if (watchId) return watchId.trim();
    }
  } catch {
    return null;
  }

  return null;
}

function getYouTubeNoCookieEmbedUrl(value) {
  const videoId = extractYouTubeVideoId(value);
  if (!videoId || !/^[A-Za-z0-9_-]{11}$/.test(videoId)) return null;
  return `https://www.youtube-nocookie.com/embed/${videoId}`;
}

function getGalleryHeading(page, emom) {
  if (page?.topIndex) return "Event Galleries";
  if (!page) return "";

  const { gallery, pathParts = [] } = page;
  return pathParts.length
    ? pathParts[pathParts.length - 1]
    : (emom?.eventsByGalleryUrl?.[gallery]?.EventName || gallery);
}

export const data = async () => {
  const emom = await loadEmomData();

  // Build pages array: each page corresponds to one node (root or subfolder)
  const pages = [];

  // summary for top-level index
  const galleriesSummary = [];

  for (const gallery of emom.galleries) {
    const files = await s3files(gallery);
    const galleryEvent = emom.eventsByGalleryUrl[gallery];

    // create summary entry (safe gallery name used in URLs)
    const safeGallery = String(gallery).trim().replace(/\/+$/, '').replace(/\//g, '-').replace(/-+$/, '');
    const galleryUrl = `/gallery/${safeGallery}/index.html`;
    galleriesSummary.push({
      gallery,
      label: galleryEvent?.EventName || gallery,
      safeGallery,
      url: galleryUrl
    });

    // Escape gallery for prefix regex
    const escGallery = gallery.replace(/[-\\/\\^$*+?.()|[\]{}]/g, "\\$&");
    const prefixRe = new RegExp(`^gallery/${escGallery}/?`);

    // Build tree: place each file in the node that corresponds to its immediate folder
    const root = makeNode();
    for (const file of files) {
      const relPath = file.key.replace(prefixRe, "");
      if (!relPath) continue;
      const parts = relPath.split("/").filter(Boolean);

      if (parts.length === 1) {
        // file is directly in the gallery root
        root.files.push(file);
      } else {
        // put the file into the node representing its immediate parent folder
        let node = root;
        for (let i = 0; i < parts.length - 1; i++) {
          const part = parts[i];
          if (!node.children.has(part)) node.children.set(part, makeNode());
          node = node.children.get(part);
        }
        node.files.push(file);
      }
    }

    // Traverse tree to emit a page entry for every node (root + each subfolder)
    function traverse(node, pathParts = []) {
      const safeParts = pathParts.map(p => safePart(p));
      const folderPath = safeParts.length ? `${safeParts.join('/')}/` : '';
      const permalink = `gallery/${safeGallery}/${folderPath}index.html`.replace(/\/{2,}/g, '/');

      // immediate children names only
      const children = Array.from(node.children.keys());

      pages.push({
        gallery,
        safeGallery,
        pathParts: [...pathParts], // original folder names (human readable)
        files: node.files,         // files directly in this folder only
        children,                  // immediate child folder names
        permalink
      });

      // Emit a separate page for each child folder
      for (const [childName, childNode] of node.children) {
        traverse(childNode, [...pathParts, childName]);
      }
    }

    traverse(root, []);
  }

  // Add top-level gallery index page (lists all galleries)
  pages.unshift({
    topIndex: true,
    galleries: galleriesSummary,
    permalink: "gallery/index.html"
  });

  return {
    layout: "main.njk",
    pagination: {
      data: "pages",
      size: 1,
      alias: "page"
    },
    eleventyComputed: {
      pageTitle: (data) => {
        const heading = getGalleryHeading(data.page, data.emom);
        if (data.page?.topIndex) return heading;
        return `gallery | ${heading}`;
      },
      description: (data) => {
        const page = data.page;
        if (page?.topIndex) return "Photo and video galleries from sydney.emom events.";
        const event = data.emom?.eventsByGalleryUrl?.[page.gallery];
        const eventName = event?.EventName || page.gallery;
        return `Gallery: ${eventName} - Photos and videos from sydney.emom`;
      },
      ogType: () => "website"
    },
    // ensure each paginated item controls its own output path
    permalink: data => data.page.permalink,
    pages
  };
};

export default async function render(data) {
  const page = data.page;
  const missingImageThumbnailUrl = data.missingImageThumbnailUrl || "/assets/img/icons/img_missing.jpg";

  // Top-level /gallery/index.html -> list of galleries
  if (page.topIndex) {
    const list = (page.galleries || []).map(g => `<li><a href="${g.url}">${g.label}</a></li>`).join("");
    return `<h2>Event Galleries</h2>\n<ul>\n${list}\n</ul>\n`;
  }

  // folder page rendering (gallery or subfolder)
  const { gallery, safeGallery, pathParts = [], files = [], children = [] } = page;

  // human readable heading
  const heading = getGalleryHeading(page, data.emom);

  // Try to find the event for this gallery (only for root gallery pages, not subfolders)
  const eventArtists = !pathParts.length && data.emom.eventsByGalleryUrl[gallery]
    ? data.emom.eventsByGalleryUrl[gallery].artists
    : [];
  const eventYouTubeEmbedUrl = !pathParts.length && data.emom.eventsByGalleryUrl[gallery]
    ? data.emom.eventsByGalleryUrl[gallery].YouTubeEmbedURL
    : null;

  // Build breadcrumb trail:
  // - "Galleries" -> /gallery/index.html
  // - gallery -> /gallery/<safeGallery>/index.html
  // - then each subfolder level
  const crumbs = [];
  crumbs.push({ name: "Galleries", url: "/gallery/index.html" });
  crumbs.push({ name: gallery, url: `/gallery/${safeGallery}/index.html` });

  const safeAcc = [];
  for (let i = 0; i < (pathParts || []).length; i++) {
    const part = pathParts[i];
    safeAcc.push(safePart(part));
    const url = `/gallery/${safeGallery}/${safeAcc.join('/')}/index.html`;
    crumbs.push({ name: part, url });
  }

  // Render breadcrumbs: all but the last are links, last is plain text
  const bcHtml = crumbs.map((c, idx) => {
    const isLast = idx === crumbs.length - 1;
    return isLast ? `<span>${c.name}</span>` : `<a href="${c.url}">${c.name}</a>`;
  }).join(' &gt; ');

  let html = `<p class="breadcrumbs">${bcHtml}</p>\n`;
  html += `<h2>Gallery: ${heading}</h2>\n`;

  const normalizedEmbedUrl = getYouTubeNoCookieEmbedUrl(eventYouTubeEmbedUrl);
  if (!pathParts.length && normalizedEmbedUrl) {
    const embedTitle = escapeHtml(`${heading} video`);
    html += `
<section class="event-video">
  <div class="event-video-embed">
    <iframe
      src="${normalizedEmbedUrl}"
      title="${embedTitle}"
      loading="lazy"
      referrerpolicy="strict-origin-when-cross-origin"
      allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share"
      allowfullscreen>
    </iframe>
  </div>
</section>
`;
  } else if (!pathParts.length && String(eventYouTubeEmbedUrl || "").trim()) {
    const safeVideoUrl = escapeHtml(String(eventYouTubeEmbedUrl).trim());
    html += `
<section class="event-video">
  <h3>Event Video</h3>
  <p><a href="${safeVideoUrl}" target="_blank" rel="noopener">Open event video</a></p>
</section>
`;
  }

  // If this is a root gallery page and there are artists, list them
  if (!pathParts.length && eventArtists.length) {
    html += `<h3>Artists</h3>\n<ul class="event-artists">\n`;
    for (const artist of eventArtists) {
      const slug = String(artist.stageName)
        .toLowerCase()
        .trim()
        .replace(/[^\w\s-]/g, '')
        .replace(/[\s_]+/g, '-')
        .replace(/^-+|-+$/g, '');
      html += `<li><a href="/artists/${slug}/index.html">${artist.stageName}</a></li>\n`;
    }
    html += `</ul>\n`;
  }

  // Sort files into video, audio, images, and other.
  const VIDEO_EXTENSIONS = new Set(['mp4', 'mov', 'mkv', 'avi', 'webm', 'flv', 'wmv', 'm4v']);
  const AUDIO_EXTENSIONS = new Set(['mp3', 'wav', 'flac', 'aac', 'm4a', 'ogg', 'opus', 'aiff', 'wma']);
  const imageFiles = (files || []).filter(f => IMAGE_EXTENSIONS.has(f.ext));
  const nonImageFiles = (files || []).filter(f => !IMAGE_EXTENSIONS.has(f.ext));
  const videoFiles = (nonImageFiles || []).filter(f => VIDEO_EXTENSIONS.has(String(f.ext).toLowerCase()));
  const audioFiles = (nonImageFiles || []).filter(f => AUDIO_EXTENSIONS.has(String(f.ext).toLowerCase()));
  const otherFiles = (nonImageFiles || []).filter(f => !VIDEO_EXTENSIONS.has(String(f.ext).toLowerCase()) && !AUDIO_EXTENSIONS.has(String(f.ext).toLowerCase()));

  let hasOfflineFiles = false;

  // If there are image files, render lightbox gallery
  if (imageFiles.length) {
    // Generate thumbnails; if generation fails, use configured missing-image fallback.
    const thumbPaths = await Promise.all(
      imageFiles.map(async (f) => {
        const thumbnail = await getImageThumbnailResult(f.url, gallery);
        return thumbnail.ok ? thumbnail.url : missingImageThumbnailUrl;
      })
    );

    const lightboxData = {
      imgPath: imageFiles.map(f => f.url),
      thumbPath: thumbPaths,
      caption: imageFiles.map(f => `${f.name} (${f.sizeFormatted})`)
    };
    html += "<h3>Images</h3>\n";
    html += lightbox(lightboxData);
  }


  // List video files
  if (videoFiles && videoFiles.length) {
    html += `<h3>Video Files</h3>\n<ul class="galleryList">\n`;
    html += videoFiles.map(f => {
      const isStandard = f.storageClass === "STANDARD";
      if (!isStandard) hasOfflineFiles = true;

      const label = isStandard
        ? `<a href="${f.url}">${f.name}</a>${f.sizeFormatted ? ` (${f.sizeFormatted})` : ""}`
        : `${f.name} (Offline)`;

      return `
      <li>
        ${f.icon || ""} ${label}
      </li>
      `;
    }).join("");
    html += `\n</ul>\n`;
  }

  // List audio files
  if (audioFiles && audioFiles.length) {
    html += `<h3>Audio Files</h3>\n<ul class="galleryList">\n`;
    html += audioFiles.map(f => {
      const isStandard = f.storageClass === "STANDARD";
      if (!isStandard) hasOfflineFiles = true;

      const label = isStandard
        ? `<a href="${f.url}">${f.name}</a>${f.sizeFormatted ? ` (${f.sizeFormatted})` : ""}`
        : `${f.name} (Offline)`;

      return `
      <li>
        ${f.icon || ""} ${label}
      </li>
      `;
    }).join("");
    html += `\n</ul>\n`;
  }

  // Then list any remaining non-video files
  if (otherFiles && otherFiles.length) {
    html += `<h3>Other Files</h3>\n<ul class="galleryList">\n`;
    html += otherFiles.map(f => {
      const isStandard = f.storageClass === "STANDARD";
      if (!isStandard) hasOfflineFiles = true;

      const label = isStandard
        ? `<a href="${f.url}">${f.name}</a>${f.sizeFormatted ? ` (${f.sizeFormatted})` : ""}`
        : `${f.name} (Offline)`;

      return `
      <li>
        ${f.icon || ""} ${label}
      </li>
      `;
    }).join("");
    html += `\n</ul>\n`;
  } else if (!imageFiles.length && !videoFiles.length && !audioFiles.length && !otherFiles.length) {
    html += `<p>No files in this folder.</p>\n`;
  }

  // Then: links to immediate child folders (each child has its own index.html page)
  if (children && children.length) {
    html += `<h3>Subfolders</h3>\n<ul>\n`;
    for (const child of children) {
      const parts = [...pathParts, child];
      const safeParts = parts.map(p => safePart(p));
      const childUrl = `/gallery/${safeGallery}/${safeParts.join('/')}/index.html`;
      html += `<li><a href="${childUrl}">${child}</a></li>\n`;
    }
    html += `</ul>\n`;
  }
  if (hasOfflineFiles) {
    html += `<p class="footnote" id="footnote">
      NB: Some files are stored offline. Please <a href="/contact/index.html">contact us</a> for access.
    </p>\n`;
  }
  return html;
}
